---
title: "Untitled"
author: "Stephanie"
date: "15/01/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r packages}
library(tidyverse)
library(sugaRbag)
```

```{r data}
shp_path <- "data/lga_2011.rda"
sf_id <- "LGA_CODE11"
focal_points <- sugaRbag::capital_cities


# Select only desired LGA areas, those from tasmania.
tas_lga <- lga_2011 %>% filter(STE_NAME11 == "Tasmania")
tas_lga[[sf_id]] <- droplevels(as.factor(tas_lga[[sf_id]]))

## Not necessary when using `create_hexmap`:
## Derive projection information
crs_info <- sf::st_crs(tas_lga)
proj4string <- crs_info$proj4string
epsg <- crs_info$epsg

## For UTM as per shape file
projstring <- paste0("+init=epsg:", epsg, " ", proj4string, collapse = "")
## if long lat is preferred to UTM, and not in proj4string:
projstring <- "+init=epsg:3112 +proj=longlat +lat_1=-18 +lat_2=-36 +lat_0=0 +lon_0=134 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs"

tas_lga <- tas_lga %>%
    sf::st_transform(., crs = projstring)

## Use the create_centroids function to find polygon centroids:
#centroids <- create_centroids(shp_sf = tas_lga, sf_id = sf_id, projstring = projstring, verbose = FALSE)

# Change this for a more detailed map
fort_tas <- fortify_sfc(tas_lga, projstring = projstring, simplify = 1)
```



```{r}
hex_size <- 0.2

lga_map <- create_hexmap(shp = tas_lga, sf_id = "LGA_CODE11", buffer_dist = NULL, filter_dist = 10, hex_size = hex_size, export_shp = FALSE, focal_points = sugaRbag::capital_cities, projstring = projstring, verbose = TRUE)

hexmap_lga <- left_join(tas_lga, 
  lga_map)
```

```{r}

hex_points_df <- lga_map %>% 
  group_by(LGA_CODE11) %>%
  nest() %>%
  mutate(hex_points = 
      map(.x = data,.f = function(a) {
        fortify_hexagon(data = a, hex_size = hex_size)})) %>%
  unnest(data) %>% 
  unnest(hex_points) %>%
  dplyr::rename(long = hexv_long,
    lat = hexv_lat)


# variable data
areasq <- bind_cols(LGA_CODE11 = tas_lga$LGA_CODE11, 
  area = tas_lga$AREA_SQKM)

hex_verts <-  hex_points_df %>%
  left_join(areasq) %>% 
  mutate(point_type = "hex") %>% 
  left_join(fort_tas %>% 
      dplyr::select(LGA_CODE11, group) %>%
      mutate(group = group))


geo_verts <- fort_tas %>% dplyr::select(LGA_CODE11, long, lat, group, order, area = AREA_SQKM) %>% 
  mutate(point_type = "polygon") %>%
  left_join(hex_verts %>% 
    dplyr::select(LGA_CODE11, hex_id) %>% distinct())

hex_animate <- full_join(hex_verts, geo_verts)
```

```{r}
library(ggplot2)
library(gganimate)

# Create static plot
ggplot(hex_animate) + 
  geom_polygon(aes(x = long, y = lat, group = group)) + facet_wrap(~point_type) + coord_equal()
ggplot() +geom_sf(data = tas_lga)
```


```{r}
# Create animated plot
hex <- ggplot(hex_animate, aes(group = LGA_CODE11)) + 
  geom_polygon(aes(x = long, y = lat, group = group, fill = area)) + theme_void() + coord_equal() + 
  transition_states(states = point_type, 
    transition_length = 1, state_length = 2) +
  ease_aes('quadratic-in') 

anim <- animate(hex)
anim
```

