---
title: "UK"
author: "Stephanie"
date: "18/07/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(ggplot2)
library(sugarbag)
```

```{r}
uk <- st_read("data/Westminster_Parliamentary_Constituencies__December_2017__Boundaries_UK.shp") %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs")
ggplot(uk) + geom_sf()
```
```{r, dpi = 300}
uk_cities <- tibble(
  cities = c("London", "Edinburgh", "Cardiff", "Belfast"), 
  longitude = c(51.50853, 55.95206, 51.48, 54.58333), 
  latitude = c(-0.12574, -3.19648, -3.18, -5.93333))

uk_hexmap <- create_hexmap(
  shp = uk,
  sf_id = "pcon17nm",
  hex_size = 0.12,
  focal_points = uk_cities,
  verbose = TRUE)

#save(uk_hexmap, file = "data/uk_hexmap.rda")
load("data/uk_hexmap.rda")

fort_hexagon <- uk_hexmap %>% 
  fortify_hexagon("pcon17nm", hex_size = 0.12)
fort_uk <- uk %>% select(-long, -lat) %>% fortify_sfc()

ukhexmap <- ggplot() + 
  geom_polygon(aes(x = long, y = lat, group = interaction(pcon17nm,polygon)), fill = "white", colour = "lightgrey", data = fort_uk) +
  geom_polygon(aes(x = long, y = lat, group = pcon17nm), fill = "grey", colour = "black",  data = fort_hexagon) +
  coord_equal() + theme_void()

ggsave(plot = ukhexmap, filename = "ukhexmap.png", device = "png", dpi = 300)
```

